# Generated by Django 5.0.6 on 2024-08-06 04:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_log',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.CharField(default='1234@', max_length=10, unique=True)),
                ('admin_pass', models.CharField(default='admin123', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('assi_id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_title', models.TextField(null=True)),
                ('div', models.TextField(null=True)),
                ('exam_time', models.TimeField()),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('duration', models.TimeField(default='20:00')),
            ],
        ),
        migrations.CreateModel(
            name='profess',
            fields=[
                ('prof_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('prof_login_id', models.CharField(max_length=50)),
                ('prof_pass', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('que_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_main', models.TextField()),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Difficult'), (4, 'Very Difficult')], default=1)),
                ('description', models.TextField(null=True)),
                ('solve_time', models.TimeField()),
                ('marks', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_names', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='in_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_put', models.CharField(max_length=50)),
                ('out_put', models.CharField(max_length=50)),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.questions')),
            ],
        ),
        migrations.CreateModel(
            name='assi_que',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.assignment')),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.questions')),
            ],
        ),
        migrations.CreateModel(
            name='stu_details',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(50)])),
                ('div', models.CharField(max_length=2)),
                ('enroll', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=150, null=True, unique=True)),
                ('stu_pass', models.CharField(max_length=128, null=True)),
                ('roll_no', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.courses')),
            ],
        ),
        migrations.CreateModel(
            name='penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('assi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.assignment')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.stu_details')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.stu_details')),
            ],
        ),
        migrations.CreateModel(
            name='exam_stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(null=True)),
                ('q2', models.IntegerField(null=True)),
                ('q3', models.IntegerField(null=True)),
                ('q4', models.IntegerField(null=True)),
                ('q5', models.IntegerField(null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.exam')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.stu_details')),
            ],
        ),
        migrations.CreateModel(
            name='assi_stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.assignment')),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.questions')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.stu_details')),
            ],
        ),
        migrations.CreateModel(
            name='stu_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_pass', models.CharField(max_length=128)),
                ('enroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logins_by_enroll', to='App01.stu_details')),
                ('stu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logins_by_stu_id', to='App01.stu_details')),
            ],
        ),
        migrations.CreateModel(
            name='Registration_t',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('experience', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('teach_pass', models.CharField(max_length=128, null=True)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.sub')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='sub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App01.sub'),
        ),
        migrations.CreateModel(
            name='prac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.questions')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.sub')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.sub'),
        ),
        migrations.CreateModel(
            name='assi_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.assignment')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.sub')),
            ],
        ),
    ]
