# Generated by Django 5.0.6 on 2024-08-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField()),
                ('student', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='App01.stu_details')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.exam')),
            ],
        ),
        migrations.CreateModel(
            name='MarkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.questions')),
                ('student', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='App01.stu_details')),
                ('test', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='App01.exam')),
            ],
        ),
    ]
